### ISSUE TITLE
It just keeps on showing this, Please reply fast. Thanks!

### ISSUE THREAD

**Issue by Uneeeeeeeee** [senhan07/V2PH#5]
Traceback (most recent call last):
  File "C:\Windows\system32\V2PH\main.py", line 42, in <module>
    get_image(album_url_folder, album_files, selected_index)
  File "C:\Windows\system32\V2PH\module\get_image.py", line 263, in get_image
    next_button[0].click()
  File "C:\Python312\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Python312\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "C:\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element is not clickable at point (744, 16973)
  (Session info: chrome=131.0.6778.110)
Stacktrace:
        GetHandleVerifier [0x00007FF6C7416CC5+28821]
        (No symbol) [0x00007FF6C7383850]
        (No symbol) [0x00007FF6C722578A]
        (No symbol) [0x00007FF6C7280E8E]
        (No symbol) [0x00007FF6C727E92C]
        (No symbol) [0x00007FF6C727BAF6]
        (No symbol) [0x00007FF6C727AA51]
        (No symbol) [0x00007FF6C726CBA0]
        (No symbol) [0x00007FF6C729F2FA]
        (No symbol) [0x00007FF6C726C3F6]
        (No symbol) [0x00007FF6C729F510]
        (No symbol) [0x00007FF6C72BF412]
        (No symbol) [0x00007FF6C729F0A3]
        (No symbol) [0x00007FF6C726A778]
        (No symbol) [0x00007FF6C726B8E1]
        GetHandleVerifier [0x00007FF6C774FCCD+3408029]
        GetHandleVerifier [0x00007FF6C776743F+3504143]
        GetHandleVerifier [0x00007FF6C775B61D+3455469]
        GetHandleVerifier [0x00007FF6C74DBDCB+835995]
        (No symbol) [0x00007FF6C738EB6F]
        (No symbol) [0x00007FF6C738A824]
        (No symbol) [0x00007FF6C738A9BD]
        (No symbol) [0x00007FF6C737A1A9]
        BaseThreadInitThunk [0x00007FFF6ED07374+20]
        RtlUserThreadStart [0x00007FFF6FB7CC91+33]

**Comment by KepalaSegitiga** [comment]
i have the same problem too
